---
- name: "Remove lasted version of Java"
  yum:
    # name: "java-1.{{ jdk_version-1 }}.0-openjdk*"
    name: java-1.*
    state: removed

- name: "Download Java"
  get_url:
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    url: "{{ oracle_jdk_url }}"
    dest: "/tmp/{{ jdk_rpm_version }}"
  when: oracle_jdk_url is defined

- name: "Install downloaded Java"
  yum:
    name: "/tmp/{{ jdk_rpm_version }}"
    state: present
  when: oracle_jdk_url is defined

- name: "Install Java from repo"
  yum:
    name: java-{{ java_version }}-openjdk
    state: present
  when: oracle_jdk_url is not defined
